version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alpha
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379

  laravel:
    image: redis:7-alpine
    restart: always
    ports:
      - 9000:9000