version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  laravel-docker:
    build: .
    container_name: laravel-docker
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - postgres
      - redis